README.md
bin/load_badges.sql

load_badges.sql inserts data for images and badges. Then, it inserts the correct image id in the badges table.

script to load badge data to db

---

app.js

* Should probably organize this better into multiple files

Add some simple routes to the app.

---

Procfile
app.js
package.json
public/index.html
templates/client.jsx
templates/pages/404.jsx
templates/pages/about.jsx
templates/pages/home.jsx
webpack.config.js

Adding react and react-router. Added endpoints: '/', '/about', and a 404. Doesn't do much yet.

Add React to project

---

Procfile
app.js
package.json

* no need to watch in production
* add clean
* sendfile -> sendFile (deprecated in express)

Update npm scripts, remove deprecated sendfile

---

public/css/main.css
public/index.html
templates/components/footer.jsx
templates/components/header.jsx
templates/components/page.jsx
templates/pages/404.jsx
templates/pages/about.jsx
templates/pages/home.jsx
templates/pages/issue.jsx

* took styles from purecss example: http://purecss.io/layouts/marketing/
* Added header / footer as a wrapper class

Added header/footer/splash

---

CONTRIBUTING.md
src/helpers.js
test/helpers.js
test/test.js

- wrote unit tests
- fixed one of the helper functions that was failing
- removed dummy fail test

Write unit tests for helpers

---

README.md

added travis badge for #39

---

README.md

Not sure we should bother keeping the 'secrets' since they are in `env.dist`.

Update readme with new env vars

---

src/helpers.js

delete entry.email wasn't working
changed to entry.email = undefined

Don't return email address to client

---

src/app.js
src/environments.js
src/helpers.js

Ran 'npm run lint'

---

test/app.js

* I removed a bunch of dummy data and added some data from @akenall

update tests to use new data

---

src/app.js
src/routes/badges/index.js
src/routes/papers/index.js
src/routes/users/index.js

In reading the code, I realized that there is a lot of tribal knowledge with how things work. I am trying to take a few passes at low hanging fruit to organize things a bit more cleanly. There are a couple benefits from modularizing the code a bit more:
1.  Multiple people can have their hands in the code with less risk of merge conflicts
2.  Much more approachable application design
3.  Easier to reuse code and less risk of duplication
Please let me know if you have any concerns with the cleanup I'm doing.

Code Cleanup and Organization: Routes

---

src/routes/badges/index.js
src/routes/papers/index.js
src/routes/users/index.js

Hey @guahanweb! I should have had you do this before I merged in your previous PR #89.
I just moved the methods around to pass jshint stuff  - you can try it out `npm run lint`
Can you review?

pass the linting

---

src/index.js

* now we can fetch badges properly again!
* not sure why tests were passing without this...

pass environment to client

---

.travis.yml

Simple ~~fix~~ change. See [here](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade) for explanation.

upgraded to container based test builds on travis

---

src/app.js
src/routes/papers/index.js
src/routes/users/index.js

* addresses #95 
@Alicole - does this address your comments in #95?

Add /count endpoints

---

README.md

paperbadger.herokupp -> badges.mozillascience

---

public/index.jade

fix mixed active content bug

---

default.env
package.json
public/css/main.css
public/index.jade
src/app.js
src/models.js
src/routes/claims/index.js
src/routes/papers/index.js
src/routes/users/index.js
templates/client.jsx
templates/components/badgeInstanceList.jsx
templates/components/badgelist.jsx
templates/pages/issue.jsx
templates/pages/paper.jsx
webpack.config.js

Publisher form work
Functionality -- send emails to authors notifying them they can claim badges. Generate id for unique url.

Publisher forms

---

package.json
src/app.js

We have mongo anyways for the claims

session work

---

src/app.js
src/routes/users/index.js

* return user info even if they're not in the database
* we only store publishers...

linting + user bug

---

src/badges/service/index.js
src/routes/papers/index.js

* added names when we create badges
Changes in badgekit:
https://github.com/acabunoc/badgekit-api/pull/1
Address #86

Names have been added to our badgekit-api-sciencelab instance

---

README.md

Change snippet in README

---

README.md
templates/components/footer.jsx
templates/pages/about.jsx

* to README, footer & about page

Add Ubiquity Press

---

src/routes/papers/index.js
src/routes/users/index.js

return 0 instead of error

---

README.md
docker-compose.yml
package.json
src/app.js

* this fixed all my weird session problems
* ... not sure why

mongo -> redis

---

public/css/main.css

Fotter Fixed

---

src/app.js

@acabunoc Because of this I was getting error yesterday 
There is a difference between /issue --> This gives error page not found and /issue/ --> This is the correct URL

Bugs with URL

---

README.md
default.env
docs/setup.md
templates/pages/paper.jsx

@acabunoc Finally everything was setup successfully and I have updated README.md with the steps to add user as publisher in the local database.

Add as a publisher

---

.eslintrc.yaml
src/app.js

As per title; small changes to comply with the [no-lonely-if](https://github.com/eslint/eslint/blob/master/docs/rules/no-lonely-if.md) rule.

changes for rule 'no-lonely-if' in new linter

---

.editorconfig
CONTRIBUTING.md

adds .editorconfig from mofo-style

---

src/routes/papers/index.js

Fixes #119

---

package.json
templates/pages/paper.jsx

Fixes #76 .
@acabunoc I have added validation test for DOI and Email ID.

Validation Error

---

test/integration/app.js

Adds one test for users and two tests for papers so we can merge #183 (please see comments there).

adds tests for refactoring pull request #183

---

README.md
default.env

With this change the local integration tests will run against a badgekit api test server.
We can close #65 and #75 as these changes will be propagated when running Badgr locally.

changes badgekit server in env file to run tests against the Test server
